### PR TITLE
Implement test for gcf rule

### PR DESCRIPTION
**Pull request by faripple**

### CODE REVIEW

**Comment by faripple** [comment]
> Could you rebase to the latest commit in main?

Done.

**Comment by schweikert** [comment]
I still see 4 commits in this pull request (including merge commits). Could you just have one commit with your changes on top of the last commit in main (i.e. rebase + squash)?

**Comment by faripple** [comment]
I am having troubles with squashing the commits. Could you do that, if possible?

**Comment by schweikert** [comment]
I recommend the following:

- Do not develop using your "main" branch in your fork. The main branch should be a mirror of what is in the upstream repo (and you can easily sync the branches in GitHub if you don't add your changes to it.
- When working on a change, create a new branch for that change.
- In this case, the easiest might be to create a new PR like this:

1. Make a copy of your changes to make sure that you don't loose them
2. Reset your main branch to be exactly what GoogleCloudPlatform:main has
3. Create a new branch and push only one commit with your change
4. Create a PR using that branch

**Comment by schweikert** [comment]
We are refactoring how rule testing works, so that it becomes easier. Please hold on with this change.

**Comment by faripple** [comment]
Rebased but commits were removed

**Pull request closed without merging**
